# https://docs.percona.com/percona-operator-for-mongodb/minikube.html
# https://docs.percona.com/percona-operator-for-mongodb/operator.html
# https://github.com/percona/percona-server-mongodb-operator/blob/main/deploy/cr.yaml

# Adding metrics collection
# https://forums.percona.com/t/collecting-metrics-using-mongodb-exporter-as-a-sidecar-in-kube-prometheus-grafana-setup-gives-only-rs0-metrics-not-the-cfg-and-mongos-metrics/35555
# https://forums.percona.com/t/how-to-collect-metrics-and-ship-to-existing-prometheus-grafana-setup/21616/11
apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: rocketchat-db-staging-cluster-v1
spec:
  crVersion: 1.20.1
  image: percona/percona-server-mongodb:7.0.18-11
  unsafeFlags:
    replsetSize: true
    mongosSize: true
  upgradeOptions:
    apply: disabled
    schedule: "0 2 * * *"
  secrets:
    users: mongodb-database-users
  enableVolumeExpansion: true
  replsets:

  - name: rs0

    size: 3
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: "synology-iscsi"
        resources:
          requests:
            storage: 3Gi
    sidecars:
    - name: mongodb-exporter 
      image: percona/mongodb_exporter:2.37
      env:
      - name: EXPORTER_USER
        valueFrom:
          secretKeyRef:
            name: minimal-cluster
            key: MONGODB_CLUSTER_MONITOR_USER
      - name: EXPORTER_PASS
        valueFrom:
          secretKeyRef:
            name: minimal-cluster
            key: MONGODB_CLUSTER_MONITOR_PASSWORD
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: MONGODB_URI
        value: "mongodb://$(EXPORTER_USER):$(EXPORTER_PASS)@$(POD_IP):27017"
      args: ["--discovering-mode", "--compatible-mode", "--collect-all", "--mongodb.uri=$(MONGODB_URI)"]

  sharding:
    enabled: false

    configsvrReplSet:
      size: 3
      affinity:
        antiAffinityTopologyKey: "none"
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: "synology-iscsi"
          resources:
            requests:
              storage: 3Gi

    mongos:
      size: 1
      affinity:
        antiAffinityTopologyKey: "none" # Needed to deploy in single node

---

apiVersion: v1
kind: Service
metadata:
  name: rocketchat-mongodb-metrics
  labels:
    app.kubernetes.io/instance: rocketchat-mongodb-metrics
    app.kubernetes.io/component: metrics
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '9216'
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: http-metrics 
    port: 9216 
    targetPort: 9216
    protocol: TCP
  selector:
    app.kubernetes.io/instance: rocketchat-db-staging-cluster-v1

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rocketchat-mongodb-servicemonitor
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: rocketchat-mongodb-metrics
    app.kubernetes.io/component: metrics
spec:
  namespaceSelector:
    matchNames:
      - rocketchat
  selector:
    matchLabels:
      app.kubernetes.io/instance: rocketchat-mongodb-metrics
      app.kubernetes.io/component: metrics
  endpoints:
  - port: http-metrics
    interval: 15s

