# https://docs.percona.com/percona-operator-for-mongodb/minikube.html
# https://docs.percona.com/percona-operator-for-mongodb/operator.html
apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: rocketchat-db-staging-cluster-v1
  namespace: rocketchat
spec:
  crVersion: 1.20.1
  image: percona/percona-server-mongodb:7.0.18-11
  unsafeFlags:
    replsetSize: true
    mongosSize: true
  upgradeOptions:
    apply: disabled
    schedule: "0 2 * * *"
  secrets:
    users: minimal-cluster
  replsets:

  - name: rs0
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: "synology-iscsi"
        resources:
          requests:
            storage: 2Gi

  sharding:
    enabled: false

    configsvrReplSet:
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: "synology-iscsi"
          resources:
            requests:
              storage: 2Gi

    mongos:
      size: 1
