apiVersion: v1
data:
    token: ENC[AES256_GCM,data:D07SgAtTHUBWm1kEwkScxSOgGfuTg16OEDjphO7sx7mE0aQ5xTXtBOK+hdyCjwdwzm9q/S5HsmHWGtcOPztKa+BzAGENRnU9XTF5wKPtKxpdw3otLGAKolewoK9yilHNajd8Y3RiKhd2OOgaQUqXAFV+RkdMsF2hrlf2D0V044Zfbhm+g+TlmBiH4ThgjAttJlHpnaOT3LkoJpH/4PuyPo2TnpwZ0Y7aDhXR9MwFqW9MfOWsyYRLU3IinO9rkGvO5hz+u/WlwGSpxnTreg5gq2L5NUW/0eOvR0GZmpSqJ85LElPdidwxII5NrpZtxhBjKJ2xgIKH1Mk=,iv:VFwb/yKNUWsn5FTkzEUBXgvxdWfbLcK2FtuLiB3YCQ4=,tag:9UtfV0AJLJu6KT+KwYncsw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare
sops:
    age:
        - recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMzdDR1B4TWUzMDhKc0NK
            Z2JHSVMzUU81eXpSRWVTbmM5Z1lOZDNvS0RNCkFHQy94NU5mTld5STYybzJzdEFM
            UjhTQkdjcjZkbWdQRlluQ0EvOTBLeHMKLS0tICs3b2JsaTluN2x3TkdpQllraFJE
            akc2cHloWGtkL2tITXo0dVpvK2dhOTgKtAMatz3hXxgjcx6rwGdnQVaBcXegf7YU
            Za+M4a0surMWdIexVum4r1g4WaigGuPN0kdu0o9RxdFmcof2QOPbqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T20:13:47Z"
    mac: ENC[AES256_GCM,data:rlbCQgqt+Z0CQrjDTLS4NBZm9RYFujSd7qMiEBSDjodAT6nIMeWGCmu1hZNW4YAWaKFHEhk8kQI2LErxXq0rGqBShKcGznH88d3Ih5W8KJOD9yBlLFk9IN3legFyaFsz1pF+bsEfu+rkxELR7dYbpXu1yJq3OVKRl47Zj1Jlgyg=,iv:MOrVn+sZ+VMtitcdmVWVYcj7ZgtfcaO+lXdYOfhpOZk=,tag:t1uJiafmw+1VpQ1iNEd7Hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
