apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  labels:
    app: cloudflared-metrics
spec:
  selector:
    pod: cloudflared
  ports:
    - name: metrics
      port: 2000
      targetPort: metrics
