apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Qom+k5ujL9nmd7VpFelNIK9hBdBRy/WLKsrOSA==,iv:r+YFz8DTl7M3RyZTbhIiqCcx5lziPL8HmSwUeRi+1wg=,tag:E/uk5w9vamlyMbvKpUdORQ==,type:str]
    user: ENC[AES256_GCM,data:0g9l/LH5l3s=,iv:LPGUDl7bT9yYBc4xQ3UrNb1L9khejA87cHyLDgku7yM=,tag:bXsvqUTsGEJspoeiGrXBjQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-secret
sops:
    age:
        - recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaUJ6N1g3dGNBakM5cUI4
            MjJvVWZGM1NhQ0I5WEw4cmd0Q256dUdFeVFZCkNVVTN0d0dRT3RyL0RFNXNGazh3
            bWZiTDVpNkRTZGJPNWp0TWJOeWZwMUUKLS0tIHVtSUFPTUExNzg3WUpPdXNnQWZa
            T3lwa3p5N1VPU2lxWG5NT1FvcDB1SDgKeRN4W4OpNWScg0lFgtY//hYe0Q6sAZix
            MIShZczgZwAeSHwxMy6AFViVrVsrR/IabfZW++6PSxlyU6zlN/mQ/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T20:29:22Z"
    mac: ENC[AES256_GCM,data:gWmFA6xemdVopf52KkaPDLf2FFzsAG4l/jCFdWaY2ioLikwYCGpmVQnpU/nTU4XMlh/MnE8kJsgQWXEJIzO/7xUtwE3kY7/QKJ63Ny6zrbFwRpjWgRFkCbe5DouSgs712u9CyfUW/xKgnAVfpAmVHn4fX7BDqt4uAK/Sap0TkzU=,iv:3UJ2ZylwGiF9sfH+m9QUZ5AUQ02yBZfCmSYTUgea8tY=,tag:phsq13QuFNhK0fZSIwNM6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
