apiVersion: v1
kind: Secret
metadata:
    name: image-sorter-configmap-enc
stringData:
    WORKOS_REDIRECT_URI: ENC[AES256_GCM,data:VgGPumlP3GgdasfFXabF1XhtRHjVRwGYVDLYYeIhbtjUwlk0C4DEfilAvtmJQUU6OR0=,iv:rmPSliz8C+NN6C85Ev49rdOviXCsPrY5eXci5EXWhA4=,tag:NHRsUaG7myNEWvDvPzYOww==,type:str]
    WORKOS_API_KEY: ENC[AES256_GCM,data:W/Ug8O1kasBk3T4VTk6WNNrR3BwXWE19tnH70skGQVkHpcdvcWweq5pthXPbN3+GXN8u/29/XhjeJhFhHnPO/hxRfR4EdLV4eMeuEIfW,iv:MIe9keUGFid09ZP8bTBecJgxvpuKLhe2Mzk8VK7ZdLU=,tag:HLxpinbgLqosx2HwN2DECw==,type:str]
    WORKOS_CLIENT_ID: ENC[AES256_GCM,data:/UwX1ZlC4JxAaPnM7r305Omz6Pj/DE28MKHncc6skKnT,iv:AHiNJ9JtOofsehOLaa1kdFANk05ZDF7Py8zl0p1VCP0=,tag:rcDTTe/2/TO0Vu2AhfUs6g==,type:str]
    WORKOS_COOKIE_PASSWORD: ENC[AES256_GCM,data:r3nXSN55qWIo0jjgHkjZTfOuVpGIyzRzbGDZwZpCouQ=,iv:WY8qmLdHzPhWocMOxxKRdxtHk5pqQwTzdGgXcpb6aHw=,tag:9cyCivVZ1saev10DRXmBKQ==,type:str]
sops:
    age:
        - recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweFFDV2wzRkcxQ2lXYWFB
            c0hiMjNDUGI2Nnp4NkdZL3hVdzUzZlhXR2xnCmtISk5aMy9LZG1wTE5XcEFRTjdI
            WTJHMmxweVlhSVdJcTBKODZHUHlBODgKLS0tIElkdW1tVEhqNERaZ1VuVkxKUEQ5
            ekVETUZHT091N0NjQU9MZDg0QVFkZlkKfpYiSYGB+kp7fgGFNXwGpgxFepApAxOu
            Z0bLOw/9z0Q4cVbvuqfVlNepdztec9viZFIGlaSeIeOuOeWmgu8zhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T21:23:03Z"
    mac: ENC[AES256_GCM,data:nzJtk7dcObAleOji7a2sJ7WHALxC4cvVffpF+VWJ3CWSgl0ibJoJlCijc2i1jhGIVGJv/SMfthp52EuYGcvBFDssvwiQJFcNGDqDZJAmBQAz/gx73iwAogiux7VvxuLp2Qhq0yStW7DcuCVGvVe8IOmONpsJ1CwcGlob+ENuRy4=,iv:0M6rg5YfCs7iimVntwmIng/5vaKq89oVkxB/hoirtA8=,tag:JVh1nGPbp4ObtO5BuRvtog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
