apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: image-sorter-certificate
spec:
  secretName: image-sorter-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - image-sorter.colddev.net
