apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry
resources:
  - ../../base/registry/

patches:
  - target:
      kind: Deployment
      name: registry
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: registry
      spec:
        template:
          spec:
            containers:
              - name: registry
                env:
                  - name: REGISTRY_PROXY_REMOTEURL
                    value: https://192.168.88.196
