apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - ../../base/n8n/
  - secret-app-user.enc.yaml

patches:
  - target:
      kind: Cluster
      name: n8n-db-production-cluster-v1
    patch: |-
      - op: replace
        path: /spec/instances
        value: 1
      - op: replace
        path: /metadata/name
        value: n8n-db-staging-cluster-v1
      - op: replace
        path: /spec/storage/pvcTemplate/storageClassName
        value: synology-iscsi
      - op: replace
        path: /spec/backup/barmanObjectStore/destinationPath
        value: s3://staging-backup-n8n-db/v1
      - op: replace
        path: /spec/externalClusters/0/barmanObjectStore/destinationPath
        value: s3://staging-backup-n8n-db/current
      - op: replace
        path: /spec/externalClusters/0/barmanObjectStore/serverName
        value: n8n-db-staging-cluster-v1

  - target:
      kind: ScheduledBackup
      name: n8n-db-backup
    patch: |-
      - op: replace
        path: /spec/cluster/name
        value: n8n-db-staging-cluster-v1
