apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - ../../base/n8n/

patches:
  - target:
      kind: Cluster
      name: n8n-db-cluster-v1
    patch: |-
      - op: replace
        path: /spec/instances
        value: 1
