apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - ../../base/n8n/
  - secret-app-user.enc.yaml

patches:
  - target:
      kind: Cluster
      name: n8n-db-production-cluster-v1
    patch: |-
      - op: replace
        path: /spec/instances
        value: 1
      - op: replace
        path: /metadata/name
        value: n8n-db-staging-cluster-v1
      - op: replace
        path: /spec/storage/pvcTemplate/storageClassName
        value: synology-iscsi
