apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-app-user-secret
stringData:
    username: ENC[AES256_GCM,data:t2bE,iv:t6a4H1a7/Sk/OAIIQuGclR+R6MhRDTQxfGSRyK4wHDg=,tag:M2lAZU4wYEGhx5FVEoQ4Yg==,type:str]
    password: ENC[AES256_GCM,data:vTwHAQbcf5PnZYu1E+c=,iv:0MREZGKDEIT/CPsKTv3c3XUiBmM0hpyCfHcpu5mhOZQ=,tag:TVXxfQcw/7SlfZSNvqtnEA==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aHltWkRSQlROczF4bWY5
            bjh4TFM1QmIrcmJiTFpud1JBYkMxMnRndlU0CnJ1S3VSNy9DemV2S0ZjZFl0bnZz
            Nm14OFNQQ1hMNnhZYTZwQnFPV1FObEUKLS0tIEFVbExwQk41UmlGN1dQOVgvTHpx
            VGx1a2xNNExvY0Z6cEsvSWZEYzIzRTgKKqyqfP+jR3M36QAm+qT59yosSDj+zAix
            /G0A93IW9oxF4SKf/mVFrcAn4n6kAa1H+PsnvsqpPR3OTITaB3B+AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-20T19:09:16Z"
    mac: ENC[AES256_GCM,data:jkxBESBQEaDmGT+CoRtRkPQ++b0NlOl83ipLFHIytaosbEj0YSXO2qV6QvTXqXUrn1n6w5cizBVyOBkPqSvk5zXj6v1Jr6Gx4ZqhTA7HjrJbi5a5bS/fRH714uIzs7bYl5osQfifgBeqU2xNCyVZ9ivJf1Idq+dAzDSCHD5a/xg=,iv:Z+dMDOXaj8/eIsJgW+LfQZQN9dPX5Piff7NAEkUlii0=,tag:K88viAkWvJqX9Smgb7HH6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
