apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hermes-agent
resources:
  - ../../base/hermes-agent/
  - secret.enc.yaml
  - cloudflared.enc.yaml
  - ../../../shared/cloudflared/
