apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secret
stringData:
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:vYhLlGxY,iv:eHCjTv1BiJzFvpIzAlUp+ZlHLowOESmBXYXJ7rRxm0I=,tag:x5dL6iw0W19Cn+XHdRs4xA==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:1RBFlF77LODssqecRMocCsB4uVTliw==,iv:903lB4kARNtIOdLeBIJMrmZ2UCKu8opEHe4xEI6RQiM=,tag:vPZiehWHBa04tNvE8f0jwg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_SECRET: ENC[AES256_GCM,data:tsLCpzj3GcwNx9B4mD5/w7iROCYqPcAIMtw1YdhaJtGczGZUvEo5lshA2ONnPkCxSk9LPGffZI/QNVa5p+zcMg==,iv:CYvM1TJ0WRQ1cZChuydFV52Y9lYgxNVxe6EO+nclU+U=,tag:bc/xUZZAQwkJdGbE8JoaWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM3psWnBTZWh2RG5oRVpB
            bWJnaXRydEdUUlNRYW9DNlRwSFQ4V2QzRGdrCjVkOU9xaWdFbWQ3TmxQWDBSb3By
            RWlzTmVpRU0vbHcwRDl2ZEt5ZFg0V28KLS0tIEl5YXd4QzZOcGg2RGxVZWhva1lM
            Y2FvL1lhNmZYTmRyTzdRdDlWT01rcVkKAPz2PX0fWtczz7Vk2ttOageOZ+hEPDYY
            pqGPYgitMEn2UkRzjgUz0TXI5eVZbzsp2uRxDA0xnhwznMVhpDu7uQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T07:37:49Z"
    mac: ENC[AES256_GCM,data:kw7Y2Ob+ePxOFseT8L84UDLkmcVamSZSmzxE/gD4zvhFYiA03R5orN1u1hJRUtlOgEghyI5GXjcIrRGgHLJFPSxmFVhC/OwavR6yTJ4bmw9agB/w1xyrPch4hWIdLXnBVJK0wPPC1RRACNz44Jvc2G4iz5AXInRTtI1TE5nokhQ=,iv:VWHNYcPwUJgH7MORrIS6W3jPLeqU+IoL3/NqiTL3khc=,tag:jp19Wpk5s2X8xywDtxnqeQ==,type:str]
    version: 3.13.1
