apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: forgejo.colddev.net/coldb/ledgerly
    newTag: pr-1@sha256:bef47031f12f1cf0f24eb72a21a57e2011d041f453cadc4e9ece26e48263f1d8
