apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - ../../base/longhorn/

patches:
  - target:
      kind: StorageClass
      name: longhorn-(delete|retain)
    patch: |-
      - op: replace
        path: /parameters/numberOfReplicas
        value: "1"

  - target:
      kind: HelmRelease
      name: longhorn
    patch: |-
      - op: replace
        path: /spec/values/defaultSettings/defaultReplicaCount
        value: "1"
      - op: add
        path: /spec/values/defaultSettings/backupTarget
        value: s3://staging-backup-longhorn@eu-north-1/
      - op: add
        path: /spec/values/defaultSettings/backupTargetCredentialSecret
        value: aws-backup-credentials
