apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - ../../base/longhorn/
  - backup-target.yaml

patches:
  - target:
      kind: StorageClass
      name: longhorn-(delete|retain|retain-backup)
    patch: |-
      - op: replace
        path: /parameters/numberOfReplicas
        value: "1"

  - target:
      kind: HelmRelease
      name: longhorn
    patch: |-
      - op: replace
        path: /spec/values/defaultSettings/defaultReplicaCount
        value: "1"

  - target:
      kind: Ingress
      name: longhorn
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: longhorn-staging.colddev.net
      - op: replace
        path: /spec/tls/0/hosts/0
        value: longhorn-staging.colddev.net

  - target:
      kind: Certificate
      name: longhorn-certificate
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: longhorn-staging.colddev.net
