apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browserless

  template:
    metadata:
      labels:
        app: browserless

    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 990
        fsGroup: 990

      containers:
        - name: browserless
          image: ghcr.io/browserless/chromium:v2.38.2

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
                name: browserless-configmap
            - secretRef:
                name: browserless-configmap-secret

          ports:
            - containerPort: 3000
              protocol: TCP

      restartPolicy: Always

