apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browserless

  template:
    metadata:
      labels:
        app: browserless

    spec:
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000

      containers:
        - name: browserless
          image: ghcr.io/browserless/chromium:2.37.0

          # securityContext:
          #   allowPrivilegeEscalation: false

          ports:
            - containerPort: 3000
              protocol: TCP

      restartPolicy: Always

