apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
stringData:
    RUNNER_SECRET: ""
    REGISTRY_HOST: ENC[AES256_GCM,data:hdRdt9SJgNPsUR54rwqf,iv:rOIBX81MZ1tgq92izu0GADFjj+p69iAjlUHjMgo/2o8=,tag:6T1AkNas3UGpLFDmM0LUZQ==,type:str]
    #ENC[AES256_GCM,data:/Q5+Z+LvbCK7SZ6kxVuAYwBxWzCxYnCfaJByiet+Ibp1Lw==,iv:QTP8ozPxQa8tLIrdHC9gOC4jdWwFL9XbyAQp971njJc=,tag:szD7qS7Og33s63o9s7d9PQ==,type:comment]
    REGISTRY_USERNAME: ENC[AES256_GCM,data:O8DukdI=,iv:QcFw/2AfzAbcG9TxQbBzN2S1loP+x6kaZFiQKMy8vUg=,tag:ODri9q+peFx4+p8OtSxHlg==,type:str]
    #ENC[AES256_GCM,data:y8IXEKFBTJFe5F0F8Yqmjhd5FkUXYd+Px/Ek8gn6dzEvPw==,iv:eKXYRU95Gy7t8kJ4dyq7yRubgvt8aFaumrMPSwFlOvo=,tag:QKfGqMGcdnw7gb37yg1jKA==,type:comment]
    REGISTRY_TOKEN: ""
sops:
    age:
        - recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTjNZWVFBcE5LQUNUVGtI
            dVRVODhZclV4ekpsUUgwcmlCWWFhOHNadlFVCnRjTkJwd01nSkZCYzJlbmw1Yko2
            bm1BT0R2U01lQ0tBd2oybTd6UFZhRE0KLS0tIEtaWi84R0dOR3dwR0sweEJWcTJt
            REVmTGJyRFlDeUxIUzI0NC94Nk1zUVkKenviL/5kxgeMmUXKmNaWPmsP5/fdnHL4
            v/EU4gF0+c4ofRL2m10r3OsX9CVHZVVyzFphRY1q8+F53o3i6fu7mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T18:38:44Z"
    mac: ENC[AES256_GCM,data:IgKn23JvGyQSzZcolFGt7+PvCjgqYYMGKbebauQHidhAu8LwzQlCBzZM3ckC07E1P6bSBSjgyiA1XB745vcekGSsUeL1tEYvlq+aXY4g4tJulvaDw0/NBO423EPpzbD2ixWy1DUlm5welvmFD7M6xZq2inl8RdgMi3eG1OiPN2U=,iv:+PO4ytK4lev/K/BLM8iKuMJLFb35QVODRos9VfmcTL0=,tag:YK2lW17w2m6w53dI627Nhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
