apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-env-secret
stringData:
    forgejo-db-username: ENC[AES256_GCM,data:EJR1qJ1Hmw==,iv:O5s4nE/Zs8rQHqdAvrEUWnZpB06tWSvje5ek/NG5zv4=,tag:I6SfAf8SUOxhjqYfl6o6bQ==,type:str]
    forgejo-db-password: ENC[AES256_GCM,data:BVrqG+zXCVPHnYK9D5Ll/J8MkGg=,iv:Fw31o/b1+AMu6kxgsOaAu+ezJytjZtiBfSekv5LTKFQ=,tag:/IpmbEu+M7xlv/+BtnzgWg==,type:str]
sops:
    age:
        - recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQTBZSmY0TXk5bUoyTjk4
            MTl2SHBqSXNENmN0My82QVNVcDhNNG9vUTA4Cnk2bWlYR0FJNzJIdGJ2MW9DSVJy
            M3JoT0ZMUUtyYk55a1BaR1RxVXZwZGMKLS0tIDV5bzRDelZLa3BBL2Eyanp5QUpC
            dDV2T1hET1BUSTZwT2l1VXRZSnFRYUEKZ+IdlcVCLgP37wD90/SnDFH6WV8FXYdo
            0IaceN3NM0hzwZ5NxOH4SW1+J5egipaD2DlvVqQ4kCD+vtSK9JgRHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T19:06:57Z"
    mac: ENC[AES256_GCM,data:4p7vNJCNHFOAqGa4koNEvG47cjPdjkxVHa+D2e+zKpRSCWLS0TQdpnPqV6lSLJ4z/+qdTZmCOrlnemYbFHF+0LdmU+4gb7/7rnYgqegdK6jCc0JvhiDyKdPMnrBpjsxJkRDJjKUQaAQiehTpqYTrQH1yQA7kbuFcrRWl2TFxx5c=,iv://zcoq489jHc9gdoQ7xg4JR+C/2yzlt0G3t637/koJI=,tag:n7QENFUTybW2yj7Qz8l/Tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
