apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-env-secret
stringData:
    forgejo-db-username: ENC[AES256_GCM,data:NwaBWAgOesVFWSGs,iv:sFmkiFtEsFeLQVR8RggqvS9iKBL7tqZiNywX7eASL6c=,tag:BGO6TEhRfjyryX884itFgA==,type:str]
    forgejo-db-password: ENC[AES256_GCM,data:BVrqG+zXCVPHnYK9D5Ll/J8MkGg=,iv:Fw31o/b1+AMu6kxgsOaAu+ezJytjZtiBfSekv5LTKFQ=,tag:/IpmbEu+M7xlv/+BtnzgWg==,type:str]
sops:
    age:
        - recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQTBZSmY0TXk5bUoyTjk4
            MTl2SHBqSXNENmN0My82QVNVcDhNNG9vUTA4Cnk2bWlYR0FJNzJIdGJ2MW9DSVJy
            M3JoT0ZMUUtyYk55a1BaR1RxVXZwZGMKLS0tIDV5bzRDelZLa3BBL2Eyanp5QUpC
            dDV2T1hET1BUSTZwT2l1VXRZSnFRYUEKZ+IdlcVCLgP37wD90/SnDFH6WV8FXYdo
            0IaceN3NM0hzwZ5NxOH4SW1+J5egipaD2DlvVqQ4kCD+vtSK9JgRHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T09:42:23Z"
    mac: ENC[AES256_GCM,data:1+srBlM7U0YHGUvHmv5hYj1cKgiVen4GAdE11g3yFDmNsihChXa5oOl12Bh7Xr4ulECQfWtYfi5ggxwdzjdntwtxq4gz6KOloJHQPrxFlOEZS3517bG/FRzAMRWTxqDXvGWOXC0Lm1pvnpxQru2ZUXd1J7LdweH41FPWBN44Q/g=,iv:sSv+ZDm0TF6S7REIK/p5B18TRftsNKb7G2k0AaQKeIw=,tag:qkAqPiME5nfMgV65diiIjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
