apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:KOWCOMg=,iv:HMOr5eizSzFNrJKPx+NB3rHMSNUDWQgCSCJGjRRI/X4=,tag:hR2uCqWm789Cz6ZaGGFc/A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:0P2CAEUjV1NiBJ4QEwbGiXh2Pd4=,iv:2QcjMzuvBW6vFVspi4DTS3vhEKcgs/QwOonnbIW217M=,tag:WR/7igtzmmhoPw/U+CzhNA==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:7jlyjXKCBxaqbTE1xda0sWPiDreYBOk=,iv:NUjw+GcYfOxLfWvuJyqCEwWUfNjqq4AB0ncbwfoiSmQ=,tag:uyUmVdi6rnH02l4gZsvXzA==,type:str]
sops:
    age:
        - recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZ1VsU08rb3RNL3drZ1da
            bk9JaWNCRGhNMXB6UkFVajV1ZHlhbm9iNWtVCllkcm9KaC9iTmVNeVV4Qm9qSFlw
            R1QzdmVIUzZ4MWljclU2dnFsRjRuSEEKLS0tIDgzZEljeXdzNlV1UzE5b3FmM0xv
            YnVndDBBUTlnZmtUWk9mM0dQbEtrdUEKfIUNLW7W/J8PE2721R9HPzqhVvgH2DFM
            RdrZTdPeYcYNJ653Bhg+QCPgjP2WYeXXog8XRTAJLYF4tEEQJnw5GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T18:35:14Z"
    mac: ENC[AES256_GCM,data:S97m5uZNqD58Y/BiFAHS3blK7B85evzH8ssMRME11iL8Owt3zoqznqfacUvl5ICoH94CAkEhTjVrYV0l/8oZYdY/LNWhZVXyiAXwXFmx+Q7P81u0RKHW9ajNMXqsSgST1OU0HCzv7mS2t9svmdjkx5HR3H4i7CzHR3uDLJHZk0w=,iv:b3SA7thwIposoHumMw7oljqJ42SsKn2UusH8obUH4cg=,tag:iJrabn+ibBfCq5hjjyfdUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
