apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-pvc
spec:
  storageClassName: "synology-iscsi-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
