apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-longhorn-pvc
spec:
  storageClassName: "longhorn-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
