apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: psmdb
  namespace: psmdb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: psmdb-operator
      version: "1.20.1"
      sourceRef:
        kind: HelmRepository
        name: psmdb
        namespace: psmdb-system
      interval: 12h
  values:
    watchAllNamespaces: true
