apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: monitoring
spec:
  secretName: grafana-tls-secret
  issuerRef:
    name: colddevnet-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - grafana-staging.colddev.net
