apiVersion: v1
kind: Service
metadata:
  name: my-local-metrics
  namespace: monitoring
spec:
  ports:
    - port: 3000
      targetPort: 3000
  clusterIP: None  # headless service

---

apiVersion: v1
kind: Endpoints
metadata:
  name: my-local-metrics
  namespace: monitoring
subsets:
  - addresses:
      - ip: 192.168.1.42  # your local machine's LAN IP
    ports:
      - port: 3000

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-local-metrics
  namespace: monitoring
  labels:
    release: prometheus  # must match your kube-prometheus-stack release name
spec:
  selector:
    matchNames:
      - my-local-metrics
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: 3000
      path: /metrics
      interval: 15s
