apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-credentials-secret
stringData:
    username: ENC[AES256_GCM,data:qdU9EEfRrJcGXgTw,iv:oHXgkONsvbv/ulEcqoIO5+cJKvw1UZptW/K/GfOVn4Y=,tag:mGy19cR/p4T/+ctF+sfGcg==,type:str]
    password: ENC[AES256_GCM,data:Y04uQHxEm2hcVXNHK0bb3WcKV1I=,iv:1M7fORpVwUPGgwjeTkGHLlsaaskQ4cUKfNgJqIVs+nQ=,tag:4Dd38U3Ue9D9B6dtwXG0HA==,type:str]
sops:
    age:
        - recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SVgwdytjTVMzYXVkaENo
            akpQMG51dWkyaGhCMERqbW1OTVdsWUZJZWwwCmdJTWFKeTd1QzhnZ0hSTXZHV1Bt
            L280aHhndXNhY0dneEVvWFhSNVNRZ1UKLS0tIHBFL3JoT1VvaDZKb1cxWm5LYzBo
            Q3FxSzhEOWp6ZzFMUkxIZWgybTNLVk0KLPdr+lih8KmWQvyw/4vJejGcEwMvDOuN
            98cusb1dWIt+o3OEUzgL1lxM+V79u/t5upG4AsHeD+1zIpbKOeaU5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T15:58:33Z"
    mac: ENC[AES256_GCM,data:ns+uoeohQVSfiCWZeDFPe76gDjhP9HCAl05SN977hYUZyBq24GRS2TmOLO09c4VH6P7gS9/faEh/54xKRNwRgEEQVYfg93wzErxrF/kqHMPnPEssMYT0nqNYmFU8AZuS2gzIYkAX9Rsu8AVrni10ZyztAmmuLjsvAfXluhPNAyg=,iv:Nt+WXDMK8+Y7fRid4M65Y1/2voX5NBYLkwv7SmAHjuo=,tag:V8+jZxyUY9SPduP9vlOUtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
