apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-credentials-secret
stringData:
    username: ENC[AES256_GCM,data:KwrJ+bc2LA==,iv:T9GwosODae4Thx5fRVcPNtQ7GE+4unUicOo6zJHjFlY=,tag:RmZn659LdINHVhwQRaw+AQ==,type:str]
    password: ENC[AES256_GCM,data:Y04uQHxEm2hcVXNHK0bb3WcKV1I=,iv:1M7fORpVwUPGgwjeTkGHLlsaaskQ4cUKfNgJqIVs+nQ=,tag:4Dd38U3Ue9D9B6dtwXG0HA==,type:str]
sops:
    age:
        - recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SVgwdytjTVMzYXVkaENo
            akpQMG51dWkyaGhCMERqbW1OTVdsWUZJZWwwCmdJTWFKeTd1QzhnZ0hSTXZHV1Bt
            L280aHhndXNhY0dneEVvWFhSNVNRZ1UKLS0tIHBFL3JoT1VvaDZKb1cxWm5LYzBo
            Q3FxSzhEOWp6ZzFMUkxIZWgybTNLVk0KLPdr+lih8KmWQvyw/4vJejGcEwMvDOuN
            98cusb1dWIt+o3OEUzgL1lxM+V79u/t5upG4AsHeD+1zIpbKOeaU5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T18:57:31Z"
    mac: ENC[AES256_GCM,data:olheA+5PsNC+gbNidIas/Z7DXNHMmfGerNbdhT+TIr6mEougkJo87Pr3A2JJlVSjmXTjb5+3lA1D/RtmYE0ua1nYllDGMIVrH9XcsDZkyzSwyzxZ5kce9HDz4mWMdt6GrttD8rcImg/fVT09uG/Mj+j4zUpTCDRHKmKGZY4v2Mg=,iv:M0tYnNc0JogAVxqMxr9wIn3pHQSSCs1taUk/hmo8wR0=,tag:NdVubZK2Wx/ZGg4/wcLb1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
