apiVersion: v1
kind: Secret
metadata:
    name: ledgerly-db-credentials-secret
stringData:
    username: ENC[AES256_GCM,data:V7E61gxlmc4=,iv:cnMj3D1lUMnLYOeSIdkP1rku1U3OAjK22H3FEPm0ooI=,tag:RKhH/G2AcY1s7zissbwQtQ==,type:str]
    password: ENC[AES256_GCM,data:RHSlsSWVs4TJVeayk/hkBXmn5Qo=,iv:fw1nnLxrnL4O6TxcwGx4ftzKCVKevaTN5xDQaRG9i7k=,tag:eJiCR8csncNo9dWyi8wU6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZXhjZlBVWG5oTTVueVUy
            blY4WXJWNWhvSVgrcnZCY3EyaUtFZ1kyYkdNCjFLb0k4bUttdnk0a3Q1R1RpcVph
            U1V2cWU3cFN0djU5M0lJMmc5UXM3K0EKLS0tIDM2K3ViQnI5NkdDelRXb21acHVm
            aWpZMG1aRUU1bkVhYXZzbmlqb2loRVEKJO0lSuaXMbeEe1J19cfO+lTIW3aj1MQu
            kYm/JDkLpSn/uapx39FfhBDROuqANUqmS6CY+o2zc+aixSA796iWhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T15:34:29Z"
    mac: ENC[AES256_GCM,data:8oSnkhQDHWgSOdXCLjqWBasg86mDUCBoewAig3125tKwIjbXdh1sZ69wSDFlqX3TLpun4QmC9NSROimTJsU/s9jbfJ3lvV0O9+Da9wwZhiJv8yRTIzuwANSPkSGKTm87zRFt6DCfadd/lpgytX6IwUmihpCrrjLciHl61K9qeQU=,iv:qbHCRlADiy71blz0JV2dugWG/JVcbg7kVG7ch/XZ8hA=,tag:hVh77iPacsVaWXLGu02i8w==,type:str]
    version: 3.13.1
