apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-credentials-secret
stringData:
    username: ENC[AES256_GCM,data:8RTqy8whDw==,iv:AnS7VhXmgFeymW1Jhbg2dZugyuwQnuVv4T0qFrIU9UU=,tag:pTpnZSUugJ8qEqbI7EiPeg==,type:str]
    password: ENC[AES256_GCM,data:hq1hsEJYyro7u2P6s3Mtpso8ELg=,iv:8Zhp2NsLmuF3WlspUnlIPzcpdm3UdmtNXKBHBDSiYkc=,tag:XfYIuQdTErbpv7hTQMMgMg==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aHltWkRSQlROczF4bWY5
            bjh4TFM1QmIrcmJiTFpud1JBYkMxMnRndlU0CnJ1S3VSNy9DemV2S0ZjZFl0bnZz
            Nm14OFNQQ1hMNnhZYTZwQnFPV1FObEUKLS0tIEFVbExwQk41UmlGN1dQOVgvTHpx
            VGx1a2xNNExvY0Z6cEsvSWZEYzIzRTgKKqyqfP+jR3M36QAm+qT59yosSDj+zAix
            /G0A93IW9oxF4SKf/mVFrcAn4n6kAa1H+PsnvsqpPR3OTITaB3B+AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T18:50:41Z"
    mac: ENC[AES256_GCM,data:TuM8bvkdNKS9HPQzICzakqMU+Z5Y18fJ0XeBcuVt9DNVP0Kf4ItyfcrCfFLCDrEl2jqYtjOnih65+HyNvECvMgdf3sECTy7EVCxAMEgXnzPyH7mxF4clipR5yoIxXuzqr4U5kYxqX0nMLtUj0ZMppiEmsXWeP60NQMBV6xq//rY=,iv:afNekuQjqSaFC/onmjyCcNCkZwaNkkRNMZw8tFqgaFQ=,tag:18cF026IxjnFWvjR8AXLnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
