apiVersion: v1
data:
    token: ENC[AES256_GCM,data:URxHAjAJ6D4kLkO7l6S002DrFujrCUXDYQLi1rQNpldtRarmglDZKEoWqUDfFEJu4j6/Eb5qqrZ7xShmzA4EEqCmONMFLbIh08bkFteICOvu0z9vW04a6yNRnB6T7sdK4wAUGUuxeAP3yKnS6mavyI+aTeAvSTKHsN3b4tpgGCqrHEdGIkF2AoMj+qvzWNhoYP0bC//7kIZcdAhJdGOy3odzc3pZ15XMS1oQTTQenBjwmivHvt2gZeqpE2StlzSbfzGqZmYWVSijSmjl0jhaVGLq4ejXXFWtNVfKYpEjjFRdoHx1Umb2oGNjAG8eBDntziEpGQgHiII=,iv:mqdNKjI4DY7hp0pAQobGHUoWfTQqsovg/IrTDTWU3Ag=,tag:qIzYqEH98oZSR8UnJNvdTg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVnFCTURUMU1nV1NhRGd6
            TU5IbmtjMnZyaFVmTmt2VUUwTk5IK3lCNTBzCkU3a3lZL3JLQ2lmdVdYR1ZuaExE
            Y1ZCbkR4RWVicGJLbSt4anE5RVZJUE0KLS0tIEpTVlpYOXlNUHcwaUl5MkxmU3pT
            OVhuTEg2bWRJVVEwSHJvSDYyQng5U0EKsZdchjevktFvNRw6wA1t2nqzrjUHncDJ
            1lt6qsF2SVXVWgHY4LGACmJHyoRFQiAJtzJN7fOu1ew31fKZi2D9bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-02T19:46:38Z"
    mac: ENC[AES256_GCM,data:P9itMWgO0vvrkukzKbCq/uOEs50ju1junLATRI5DbC9X+qhNmD0OcIFd7hl7JIOYVaKgWBO46QGfJUA0HClq53j0lWaCVgeYnpqo6Py/qHvNZJFc3iilHsg4ibJKwsXH4IiaC4ooWOg9wvg2vco3rMwEAp2cPmbMYFDzD05Fk1c=,iv:4BXyhcEfJMpuQOFGTjU/9mTOYG5hks4m4FP0zVWwmmw=,tag:hlI/uuuIz44DJno0Bvgp8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
