apiVersion: v1
kind: Secret
metadata:
    name: aws-backup-credentials
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:x0XJ1yHxv02dQFUEULn0fcw4b64=,iv:yxIhExIRoI9kpheS4xoiiaRnX6J4eir3HYUiJX+3fSI=,tag:xolD1T8Em8WwIug+cuRqbg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tCp0WTH9erKUZNKrr1cO7hOJC7FnCyhuGs+/FDifzX9eUKQQx+UlkQ==,iv:wElxQZEILrhALqv59EJjRiFIZvOpy+LwtbwzSkQCYWE=,tag:JkbCbejqXAiklFPyfS9rDQ==,type:str]
sops:
    age:
        - recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvajQ4TnlhUkdxZnEyWGpE
            MXp6K3crYU9xSDNoT1RIdHBSNVBvM2VUYlFvCnd6NFU4MGxNS2hOYmtrYWFuN2dj
            RHNYWGJZSnVRVmlRcHZoL3FvUzM0V0EKLS0tIEFScmMyT2ZSeVRlcVdrdUpXUzdy
            WCttd3NrdlZzUG9YajlZZ1pEaEwzM0kKXMyh1qtTev6FttWC36lN9XenZgJtIiyz
            zVxfUm09foADJU+jOq70+OWcGYmJT5WdC7kwomPnRhHOdcSIf34Rtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T16:39:20Z"
    mac: ENC[AES256_GCM,data:EzNSroOTWCa7Sn/qOZZsk2iNZeszgZJVK7RsBVXgPO5wEFoY5xC0V7ob2uFdkrQKrF5EiFVTFZcPz0HpBGpHUExM83coZkB2aTaCO5wftfX42SaMF0kgAT+nXcaosCgMluHlmRETsDxZe2Ifvnh+5YburgW1Ckx2AtH2sHwt8c0=,iv:i3+rpcvULl6QU6pCtiGXdIjQmwd23pZr+TIr6eHHJqM=,tag:CokO27Zn7TopbEELAzcTjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
