apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin
resources:
  - ../../base/pgadmin/
  - secret.enc.yaml

patches:
  - target:
      kind: Certificate
      name: grafana-certificate
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: grafana-staging.colddev.net
