apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin
resources:
  - ../../base/pgadmin/
  - secret-configmap.enc.yaml

patches:
  - target:
      kind: Certificate
      name: grafana-certificate
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: pgadmin-staging.colddev.net

  - target:
      kind: Ingress
      name: pgadmin
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: pgadmin-staging.colddev.net
      - op: replace
        path: /spec/tls/0/tls/0/hosts/0
        value: pgadmin-staging.colddev.net
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pgadmin-staging.colddev.net

  - target:
      kind: PersistentVolumeClaim
      name: pgadmin-data
    patch: |-
      - op: replace
        path: /metadata/name
        value: pgadmin-data-longhorn-pvc
      - op: replace
        path: /spec/storageClassName
        value: longhorn-retain
  - target:
      kind: Deployment
      name: pgadmin
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: pgadmin-data-longhorn-pvc
