apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-sorter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: image-sorter
  template:
    metadata:
      labels:
        app: image-sorter
    spec:
      imagePullSecrets:
        - name: docker-registry-auth
      containers:
        - name: image-sorter
          image: forgejo.colddev.net/coldb/image-sorter:latest@sha256:c0ef347314cf5465079aea7f4bc83357fadcabb06165c4d3547922718c320df0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: image-sorter-configmap-enc
          ports:
            - containerPort: 3000
