apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-sorter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: image-sorter
  template:
    metadata:
      labels:
        app: image-sorter
    spec:
      imagePullSecrets:
        - name: docker-registry-auth
      containers:
        - name: image-sorter
          image: forgejo.colddev.net/coldb/image-sorter:latest@sha256:3b216b44c2a23399322e089af5bc9f0be8b890ca09c0d00c594e357b6ff462e8
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: image-sorter-configmap-enc
          ports:
            - containerPort: 3000
