apiVersion: v1
data:
    token: ENC[AES256_GCM,data:5/rlYlAZ4UG7oAcKXb+aDLjBWpk4ihKRkVdaopNEDIyZflG329RegJVyVK+YDyDub0duWBYbaKy8PhPGd8N6GvrQF7Gj0o7/Qi/AqfZtYtMpTtI/xqZQBv0QMXuSCqHyKu4gANnHMlm4GwOB7GkS8XW65mny5yTq568rOQbGtzhbUTdxs+F8Ek3WYhGEjmpHP4aifTSoSvUHRumPyHs79cpxUD8QLdQiIV4tan/p88zzA4vwZihe3qhl0epO0QUniFHMZ5PmQzoI2jTiAYJUJRDcS8fiX4eRTK2oisSYkGkyUhl19+KcTtgYLKRX6yneANuRsiPWaxw=,iv:DUEvasoYmVo8KGJq3EFu8habLaRsqfQDMRrxAkmXwHA=,tag:Hy/woenRTNMDqMhKX+ayOw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare
sops:
    age:
        - recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUEdoc2VBRzFEOFoxTFNy
            QjlVUXhtYWc2SnpTQXRiQ0E0dkpLbVZ0RkNFClc0VjlYMG93YVlQNFlZb2JWYkkz
            TDRINnl5Uy9pdFBFcklVQ0dKRXdZZU0KLS0tIEw2Z1poR2Q1eE03U0hiZ2cyNUlU
            SElBR0Q0YlNvUDZBbTBtNWpYczJRZnMKCQPQ1GPenyElGNoGORoP1QQX1SGs4HIm
            dX5d2NuBEwmZt7c+9+dtbUVEHPArM1SCunAnSM1K4GXUr41w3yYQMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-22T16:54:37Z"
    mac: ENC[AES256_GCM,data:LX8IVYbnFN/37Q2eV06OHRjyTBGBSW1d5+I5Sc1hbfFlzHfvmNd/KB6fihpRh0KKHdmBS4THTm9p+5dd5NpVL7wa7kxpzFsXgkzY+YtzTDu9vSZWYYpEMu0KIT/Lw2XYoev5HWnw3eJS0FSl8P3ZbqiZIRVinZFwHPLWng3YlB4=,iv:eaOcfWaCUEk0FR1s6JQDD9hXxQhf+uyhs7CZTz1+MRI=,tag:uKld02X5ieWWnrCJJGpnAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
