apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-certificate
  namespace: registry
spec:
  secretName: registry-ca-tls-secret
  issuerRef:
    name: colddevnet-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - registry.colddev.net
