apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage-pvc
spec:
  storageClassName: "synology-iscsi-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
