apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-home-data-longhorn-pvc
spec:
  storageClassName: "longhorn-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-home-creative-data-longhorn-pvc
spec:
  storageClassName: "longhorn-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
