apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-home-data-pvc
spec:
  storageClassName: "synology-iscsi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
