apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: forgejo.colddev.net/coldb/ledgerly
    newTag: pr-1@sha256:83ebe8fa41df2ca3021c277e1e85939fde5d5da9e5f8478763cde051ddce781f
