apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
data:
  config.yaml: |
    log:
      level: info

    runner:
      file: .runner
      capacity: 1
      timeout: 3h
      insecure: false
      fetch_timeout: 5s
      fetch_interval: 2s
      envs:
        DOCKER_HOST: tcp://localhost:2375
        REGISTRY_HOST: ${REGISTRY_HOST}
        REGISTRY_USERNAME: ${REGISTRY_USERNAME}
        REGISTRY_TOKEN: ${REGISTRY_TOKEN}
      labels:
        - "docker:docker://ghcr.io/catthehacker/ubuntu:act-22.04"
        - "ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-22.04"

    cache:
      enabled: true
      dir: /data/cache

    container:
      network: host
      privileged: false
      options: "-e REGISTRY_HOST=${REGISTRY_HOST} -e REGISTRY_USERNAME=${REGISTRY_USERNAME} -e REGISTRY_TOKEN=${REGISTRY_TOKEN}"
      docker_host: tcp://localhost:2375
