apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-docker-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn-retain
