apiVersion: v1
kind: Secret
metadata:
    name: ledgerly-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:qZcua2rDOR8Y26kHBaREc9dHZrhAQumsRgwGd3NnZkHLJYSJIgjwAxaHvi0KorZ3qRPFS2ZEOufBBOVkZXEn/WhPb0w4GoSNNCufXDb2kP8cpV0xLDEhHPeF1HSUs13lJ+qYW9vUccYVicWCQameYn88CrcHbg==,iv:3Iwp+57iaxby1ZzHDG+L1KV/PtM8ahQ4ayW2s/IjlZk=,tag:OwVyIcv8h+kIzjW9p8nttw==,type:str]
    CLERK_PUBLISHABLE_KEY: ENC[AES256_GCM,data:vWw0P0H/ourYYNggbRjzKj3YDWd2bjPqFRpeUo2X9ngmGoRSjmPN5XrI,iv:aHcLURNtstmoUkPckXSoj0BSGtCIGstZL+a9vIuq2Ho=,tag:FYIMG8L3KD9qZ+45wXGXeg==,type:str]
    CLERK_SECRET_KEY: ENC[AES256_GCM,data:eOUtwdeMqltXuWO6atzI1XDwTV7AQhB5mo1lQbG1DdHQyURTumlV8JLoVyCunGTYJt0=,iv:rtilqhp/bP8rA3rsodPNI4xg4swTYAgq6qpjSee/L3o=,tag:8qdebkVXrPSJgcRWY8S4/w==,type:str]
    GT_PROJECT_ID: ENC[AES256_GCM,data:uyKtBuQXUoT0jZUr0QJZAxT4xCxp7lOFWBElaw==,iv:VOKHlEL6gudOWy1Fu5rZkXQwUtlZqMfh9jc8ENp39QU=,tag:ENVX8cBfsnP4JwG97rDnew==,type:str]
    GT_API_KEY: ENC[AES256_GCM,data:00TjZ20ffDKehFfmkyZNIrEYcPLnIjp2RvrYjx3gb15i4412pCVDvJfwTRbpWV2kdII5BpjrAQdWH9HYipl+EVGLV0RMjO9g,iv:SQrCf/7GvMRZP2S3ZKdU76XzYIoBKMtKRlSZE2c3dmU=,tag:7f5R8PlkKDDFwpBzk9q5Tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNXF3dlNBN0Uwa1pFWVVJ
            bkNvMXNNQzUrVnYwSVQyRHorRzNXSTJWZ1ZzCkRlc2VtVDRFRkthRmFYSjNlb0ln
            RS9nN01hWUx4K2d1UVFCcUZTSDUwMEUKLS0tIC9JRUJpekRpQ0Z6TExnSVkrZVRP
            VEhQbGxMajc2a3VOd0pyOG90Z0Y3eU0KuKj1x5v8v9xjpikxvy5FLxmqvonkGTsq
            U7aqhrY6h44UnYeBECpSeM2DOrbbbb8OdtMkp+cK1VNzkG/HEAZRSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T18:38:09Z"
    mac: ENC[AES256_GCM,data:gVWp+UwSgVUIU13OJZVwmusoILQ66IVzakLs0lbLnos4KinRO6py8ZhnoXb2X96FOUhz5t3hxZj+5/smCVQiFqogLz4MmBXf/bevNIG7AgZjoojlxnDQtUKuZLmXX+zV9NlRlDiRmdXCi6vhIbmfa2yGMc1IcqX2I5e9lK7kBTU=,iv:vpND5ceqAhPgo4emj/nEfTUF6Lv8lkSshaD4YnsGce8=,tag:jJBZufaZ9NN5dp54kTpVSQ==,type:str]
    version: 3.13.1
