apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-public
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: testing-public
  template:
    metadata:
      labels:
        app: testing-public
    spec:
      imagePullSecrets:
        - name: docker-registry-auth
      containers:
        - name: testing-public
          image: forgejo-staging.colddev.net/coldb/testing-public:latest@sha256:a2303fc6724c46c4094837a596324c8734004efcc3b43e2e9455f4321d63664b
          imagePullPolicy: Always
          ports:
            - containerPort: 80
