apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo
spec:
  ingressClassName: traefik
  rules:
    - host: forgejo.colddev.net
      http:
        paths:
          - backend:
              service:
                name: forgejo
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - forgejo.colddev.net
      secretName: forgejo-ca-tls-secret
