apiVersion: v1
kind: Service
metadata:
  name: rocketchat
  labels:
    app.kubernetes.io/instance: rocketchat-metrics
    app.kubernetes.io/component: metrics
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
    - name: metrics
      port: 9458
      targetPort: metrics
  selector:
    app: rocketchat
  type: ClusterIP

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rocketchat-servicemonitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - rocketchat
  selector:
    matchLabels:
      app.kubernetes.io/instance: rocketchat-metrics
      app.kubernetes.io/component: metrics
  endpoints:
  - port: metrics
    interval: 30s
    relabelings:
      - targetLabel: cluster
        replacement: "production"
      - targetLabel: tenant_id
        replacement: "production"


