apiVersion: v1
kind: Service
metadata:
  name: rocketchat
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
    - name: metrics
      port: 9458
      targetPort: metrics
  selector:
    app: rocketchat
  type: ClusterIP
