apiVersion: v1
kind: Secret
metadata:
    name: forgejo-configmap-secret
stringData:
    FORGEJO__database__DB_TYPE: ENC[AES256_GCM,data:bVItFqyXiXU=,iv:z1hiVLU7hgmagl68sqIfyPirU6gjIvWqNSoYpWqm1yk=,tag:k5xT575xNIcoyauoz5WqtQ==,type:str]
    FORGEJO__database__HOST: ENC[AES256_GCM,data:zx2TfjSSs65kaup99mzpaj0gAbce/QHtlCgPbi6Cio/1aSZfNlCw2p14eq7zPh20cqUACbXITPxcSWOD4yGe,iv:oNp7AG9DkInAKIPILzCCprqBQ686oXwrNneAXX+gPC0=,tag:W1tGHYZ4SilkgzA73jpbyg==,type:str]
    FORGEJO__database__NAME: ENC[AES256_GCM,data:aW427tbSGw==,iv:55L61Z/KImm5tT8N2nuT3PvabQn2kDEaV/8aHYsvoUA=,tag:2hwj3ENQ2eSCvqPoCltA8g==,type:str]
    FORGEJO__server__DOMAIN: ENC[AES256_GCM,data:Ue45nKawTVP6ijL013cYdbPzqKWyW0Oiv6b0,iv:N/EtZvCvyVfT99Zg0dgKgdJ489nihIlm/gius4nIXfI=,tag:vtrCqL94REeP3xsOfq/cdQ==,type:str]
    FORGEJO__server__ROOT_URL: ENC[AES256_GCM,data:FCVBX7MdxeEtaFTrye5ODvkTrwRdog3qmnTzooJ2hhnN5MmX,iv:1ZXalf6pxBp6eYF6wkJT/2K/fCtLmITdy7wefLZIwlw=,tag:ZLjS59g3SPyssnsLaPwjoA==,type:str]
    FORGEJO__server__SSH_DOMAIN: ENC[AES256_GCM,data:Yk28H94d0AZ7iK2Qg5lOCErnw5tDrjo=,iv:6DSqBwr5ViaB7B++eK/5K/k6xiZFXgfkPbVQJaWAZuY=,tag:5vxuIhzmYPkDkcdZp2BdrQ==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5U3lwSnplZEJ6WnQ0WXZF
            U3hOYXlhRDhETEREc05CeVoyTFRzeHlTQ1JFCndtU3ZaWTBXTGpxOGE5bmtHeEtn
            VWlsUFpRZzhJQTRRYzQyZVhiQ1haMjgKLS0tIFFVL3BFT0ZPMDlOM0NsWWt3R2xk
            WlVUOURSNVJINVdUSTdoM1l6TExyKzAKAZYZ9IYetebJ0o9r+6TM2SPPWAN0yvs9
            dVYInL1Qm116qloGMCgNReJYts3JWw4t/5SunxVgDBWRK10umWhlxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T18:16:01Z"
    mac: ENC[AES256_GCM,data:01Yug12yo5WPint1+53oNFoKwrMOwiIg7awCVuf3a/u61IgvStpOO3lb4e05X/kFeuUBk8oJV63+TGsGsfojeZB0rN/TY8L5Yt+2tsyASZOA/pmxtF7axjwe1cJtieKYveGntGIMSvGmJbumMjPPWQBVn+2HixzpoFd3Xi3pzBk=,iv:V0ghrgKQoFD8vW9FpiQvcVKE7o0iJVozZyP9anAOArU=,tag:A9wM1QGVqAHRTd4YEzbdbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
