apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-env-secret
stringData:
    FORGEJO__database__USER: ENC[AES256_GCM,data:DW8pLWOwuw==,iv:/O70p5HHCCAg6+i2HA3i14gRkBXYUT0P0CQZnmWKyNI=,tag:cq4UqE+fGFfAIMvrfvTwAw==,type:str]
    FORGEJO__database__PASSWD: ENC[AES256_GCM,data:7nnb82d8SiVn7SF0pBVhofzdl5o=,iv:FLzgvQ9oeWUHvPs9bUZDBYgtMewTRjTPbwBp4Sb+ciE=,tag:EErxSMUz/3MutSfWfD2NgQ==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWUtFRktoK0xKc09ia3dO
            NEZDUHh4OGxjSnFuZlVVWE5XTkdhaVlMVDE0CjlOUzVLcW9WTHVCZlNQSEhRNUk5
            eTk0bHk4NDNiN1J3SjBvdjJQZkswUjQKLS0tIGVSQ0wwdGFZZXRYOW9vaklVTVc4
            MGhPYmVQYkNWNDVNenlVMnNtRUJmdzgKu3cAVIobJF3uU/uHcivkuOyNDB01lsn1
            RzIx6Z2zd0jgSkATjyNtawh0KQnbXqolpORW2TNyJXWX3YejL88UXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T18:51:03Z"
    mac: ENC[AES256_GCM,data:QmJZ0qZM5L4R1nTKTJXRWkQyOYEgP8p3gztC8Kt9R1mdz1XzymKZgXU9Bhlmf+Lp/U0v2gQ8ZlaoyyEzHaaf4/+Ypt1kkXRX95v2rvTQ9D2FLGi2VZjLOStaCwo3Rx9ta/voYoM1Cqa8Zwhf6JYN4w/l1rw4sL/GOS0wKZHERpg=,iv:A+G0bZxYkd/QIUkNKoIaPox5cpegPPxku1hlhY0Qp8M=,tag:oqMU5u9F0q0EnYduWlAxGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
