apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
stringData:
    RUNNER_SECRET: ENC[AES256_GCM,data:YqW7yqypezse5EGc57PjzqmbY2rT2Vz5r012i8YRm/C96UtkzVruQQ==,iv:emcIpFD9wQuuY2SthTWH1LuOuZ+/GIOCAM+us1Q7zjA=,tag:hd9/wKxCBeHvrmjtnQ5cog==,type:str]
    REGISTRY_HOST: ENC[AES256_GCM,data:wPrm6+OYSLLrSj6G2QzvInG+lhUBBQ0=,iv:NwZqj+jYYKO43lJWx5vVYUJm6Eu3pF08fo2M/QLnIQM=,tag:Y0RRThrDrsTdfRYfCxlIOQ==,type:str]
    #ENC[AES256_GCM,data:McmctM50cIV6euIQvu/pMm/YCz9X/BTvEZhf1T1Hfj9nnQ==,iv:I0pV+4ZvjKU7/tYjF3H/SZ+Ms6xPd1b+QDNuZbFiJIU=,tag:B2uJysZAJMA5W1rIuNa2hQ==,type:comment]
    REGISTRY_USERNAME: ENC[AES256_GCM,data:p/9FMZE=,iv:p5RUwhAWLp4K+OXOF3uTfvb/tlai68aINw+aXuDyVTo=,tag:b8PMWTwd4j9xct50mkAlxw==,type:str]
    #ENC[AES256_GCM,data:jh+U+H5SSwykBswlxqVTwn1BW/OoRdfo2ao6SUUd2JHexg==,iv:l1HtlNfYmfFamQdLHSbyE3furutLVp/3i21+mGIu+Qo=,tag:Rr4WF8wl7jmgWMupx8Mz+w==,type:comment]
    REGISTRY_TOKEN: ENC[AES256_GCM,data:gsm+mASHXR9Vyhd47kbeluI2YZLJw3PPXtcdHhPPM2wPj4XlP3A5ow==,iv:wRj/yXXvl0Cw3IhKWszHFhljpM2KcEw8Ak3mHY2OsqI=,tag:7nZWBs0tB0lRJaVZvXD53A==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsM1BaNUIvRkk1NkErL3lM
            UU1VRGl0OTRCK25Vd0FuS21ibVFxMWZpTUV3Ck0zd0hpN2lHZGEzaWs1bzhDM1lR
            VGJBNDNxQklQZTI5QWpOUytmUFBxdEkKLS0tIEIrQWFQNzJZN3pIcVZ5VmgwZytU
            ZXUrS3hqekRqS0NBTUxXWUxYWnhNbHcKsS9U/nxpjxq5GPOEeTQqkH3L0TxI+vdg
            ArR370w/16uCOBd1lie6Lzn6KmXD+Gc6ZtbJkF83XJMNEQ4EQ2Xi5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T10:12:29Z"
    mac: ENC[AES256_GCM,data:c9O0mPNjClM48AbR8BJJprIB6WlQNRtf5/NhzhI1J77zoN8r8brwT/AfNGlzyAHBckgDgTusTvYJ8Hh5qS+Dx9hZsxDnlueyqE6HtXBeyc4KBlge1HW1kocwblG6kyEf8G9qMajn50lfcqKxHh+hHTOyl3LOvEbY9dLg8sFhhQI=,iv:8c7fsCPbYJgCJZH9BHtXStMHVRj0k3OdyCttVGABdKI=,tag:Z8tIJWXrl8R2GYwyVz0uTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
