apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
stringData:
    RUNNER_SECRET: ENC[AES256_GCM,data:YqW7yqypezse5EGc57PjzqmbY2rT2Vz5r012i8YRm/C96UtkzVruQQ==,iv:emcIpFD9wQuuY2SthTWH1LuOuZ+/GIOCAM+us1Q7zjA=,tag:hd9/wKxCBeHvrmjtnQ5cog==,type:str]
    REGISTRY_HOST: ENC[AES256_GCM,data:wPrm6+OYSLLrSj6G2QzvInG+lhUBBQ0=,iv:NwZqj+jYYKO43lJWx5vVYUJm6Eu3pF08fo2M/QLnIQM=,tag:Y0RRThrDrsTdfRYfCxlIOQ==,type:str]
    #ENC[AES256_GCM,data:McmctM50cIV6euIQvu/pMm/YCz9X/BTvEZhf1T1Hfj9nnQ==,iv:I0pV+4ZvjKU7/tYjF3H/SZ+Ms6xPd1b+QDNuZbFiJIU=,tag:B2uJysZAJMA5W1rIuNa2hQ==,type:comment]
    REGISTRY_USERNAME: ENC[AES256_GCM,data:p/9FMZE=,iv:p5RUwhAWLp4K+OXOF3uTfvb/tlai68aINw+aXuDyVTo=,tag:b8PMWTwd4j9xct50mkAlxw==,type:str]
    #ENC[AES256_GCM,data:jh+U+H5SSwykBswlxqVTwn1BW/OoRdfo2ao6SUUd2JHexg==,iv:l1HtlNfYmfFamQdLHSbyE3furutLVp/3i21+mGIu+Qo=,tag:Rr4WF8wl7jmgWMupx8Mz+w==,type:comment]
    REGISTRY_TOKEN: ENC[AES256_GCM,data:B2te869lao28uaFJDvGcgXyMd9r+RR1Mar2bx2GcIboemT8HUeApkQ==,iv:mTCrvBrECricOygUjqsW4uzpBDwUiEK616NHnGV0nDE=,tag:RCNxNWd5Jvr2FYm+k13TTg==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsM1BaNUIvRkk1NkErL3lM
            UU1VRGl0OTRCK25Vd0FuS21ibVFxMWZpTUV3Ck0zd0hpN2lHZGEzaWs1bzhDM1lR
            VGJBNDNxQklQZTI5QWpOUytmUFBxdEkKLS0tIEIrQWFQNzJZN3pIcVZ5VmgwZytU
            ZXUrS3hqekRqS0NBTUxXWUxYWnhNbHcKsS9U/nxpjxq5GPOEeTQqkH3L0TxI+vdg
            ArR370w/16uCOBd1lie6Lzn6KmXD+Gc6ZtbJkF83XJMNEQ4EQ2Xi5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T11:50:21Z"
    mac: ENC[AES256_GCM,data:+yb84hT2f1I2lImbWncqVdlSpWWsz8x8LBd289xOwfa0iEE2PI6s8YQTxXDi8bXGbRftlqnEOPMExylJeYNW8U3IIcNSaesPvSilOsujoWclfnN5+Q2ZNKUybbuhNUlhgSNkulY6td3nVqjL4mxEknzaX6rML6RRqR9qJZAh0Bg=,iv:fHuz2/7tTjTdyqc7beU2tNqkFefRzCP0ztZugotARmE=,tag:DKCb4zIUEaIhBrG1ci5DYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
