apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-env-secret
stringData:
    forgejo-db-username: ENC[AES256_GCM,data:dW2+zlHLX03TmtzI,iv:ldJXjopek88VvPa0OnZt//JPhi7OB0auML9N5/2ffO4=,tag:CM6q9XEVQUDmFUTKk8XkuA==,type:str]
    forgejo-db-password: ENC[AES256_GCM,data:pSnrAIecY8r24uQAoNZ9+bAbOYU=,iv:Mj+sgvD9fEESyQsvPw/0wE5k/tREPPMtUnucyqZ1Wpo=,tag:3gjoaql3cSg1kbuq6uh/1Q==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWUtFRktoK0xKc09ia3dO
            NEZDUHh4OGxjSnFuZlVVWE5XTkdhaVlMVDE0CjlOUzVLcW9WTHVCZlNQSEhRNUk5
            eTk0bHk4NDNiN1J3SjBvdjJQZkswUjQKLS0tIGVSQ0wwdGFZZXRYOW9vaklVTVc4
            MGhPYmVQYkNWNDVNenlVMnNtRUJmdzgKu3cAVIobJF3uU/uHcivkuOyNDB01lsn1
            RzIx6Z2zd0jgSkATjyNtawh0KQnbXqolpORW2TNyJXWX3YejL88UXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T09:41:59Z"
    mac: ENC[AES256_GCM,data:uMoEwpWDsQ5MDt8uoiz/AiqFFikin950+7qQtxItHnoiGgj4AKeooazN/Ky0ozJCvPytZ6TLvNFqhkG640U8MF5/KkkvG7+f90NuEAUllz9THhMjsEfjwgYk9RVODvCnQjkUAXqqCZdG9LmgVUFykGlrBDIxAWtsKuU4zIaUeZ8=,iv:A+QLJ9QWdOiwCSZ/QqfwXaocIrwDl5KwUASL0UjZ3/g=,tag:j8EIRYocm5Dork1K0odkzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
