apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-env-secret
stringData:
    FORGEJO-database-USER: ENC[AES256_GCM,data:vdVGalSra3lxT9pk,iv:mokvZPVLWB4MPRuz2Xg1hS+oXgIdvPNxXWIbfbHBiec=,tag:rWrp5eRYWEEVqsua9n9vpA==,type:str]
    FORGEJO-database-PASSWD: ENC[AES256_GCM,data:/6yI/edsH608shTZt28OCWscj6I=,iv:FDGLIvyeZUcvRKz1H/QwANBIs+gtQ4V0QCp6/r7+LRc=,tag:i1Av7IKtM/5mwlMV6qhBuw==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWUtFRktoK0xKc09ia3dO
            NEZDUHh4OGxjSnFuZlVVWE5XTkdhaVlMVDE0CjlOUzVLcW9WTHVCZlNQSEhRNUk5
            eTk0bHk4NDNiN1J3SjBvdjJQZkswUjQKLS0tIGVSQ0wwdGFZZXRYOW9vaklVTVc4
            MGhPYmVQYkNWNDVNenlVMnNtRUJmdzgKu3cAVIobJF3uU/uHcivkuOyNDB01lsn1
            RzIx6Z2zd0jgSkATjyNtawh0KQnbXqolpORW2TNyJXWX3YejL88UXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T18:07:30Z"
    mac: ENC[AES256_GCM,data:YL7UgBk/BAe2LF152XJ+da4S0XtRgd+LtvXXTCT7jwz+TncLNOAb5t1Ul477wLbMYEdGxuhLf3UQM4E9ED36exwIDSi10ym12A1GF3mILFKDBXxl68JUCsNRvu7IODVIh6Xs7/1858VdEv75yV3d5/wkBjpM/tfFS0KWkPNA8ZI=,iv:JaRl5xpgaGpPgZu7ZIDiM5/t8tALOY6a75jJ/uv6eVk=,tag:3Pku28S2M3KPQTZ3N00x5A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
