apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
stringData:
    RUNNER_SECRET: ENC[AES256_GCM,data:YqW7yqypezse5EGc57PjzqmbY2rT2Vz5r012i8YRm/C96UtkzVruQQ==,iv:emcIpFD9wQuuY2SthTWH1LuOuZ+/GIOCAM+us1Q7zjA=,tag:hd9/wKxCBeHvrmjtnQ5cog==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsM1BaNUIvRkk1NkErL3lM
            UU1VRGl0OTRCK25Vd0FuS21ibVFxMWZpTUV3Ck0zd0hpN2lHZGEzaWs1bzhDM1lR
            VGJBNDNxQklQZTI5QWpOUytmUFBxdEkKLS0tIEIrQWFQNzJZN3pIcVZ5VmgwZytU
            ZXUrS3hqekRqS0NBTUxXWUxYWnhNbHcKsS9U/nxpjxq5GPOEeTQqkH3L0TxI+vdg
            ArR370w/16uCOBd1lie6Lzn6KmXD+Gc6ZtbJkF83XJMNEQ4EQ2Xi5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T17:47:29Z"
    mac: ENC[AES256_GCM,data:kiLZBTCXShBEpBEUyPpSNIn2lK+xf77+WmoKQ0fJXfgPVx2X7BRjzYjPw+E87hljgQR1fW5zVP46NAmhP2CvMhLAmdyO6IlIOPUYxMpoYQaxN+M2SPRZ6t7FdzNlPuxyzkAsB+iJ8Eksok835bRU3FX+0WMmq6SAwQV8RY+RCWQ=,iv:t2aoFvuSSdIU4o+0M8rtVxxs/tQGKzLHEvAd5GZ0TVc=,tag:nCdzgJyvNL041c+0FgdwdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
