apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:TIWlHiA=,iv:Iux+139KylO8upRUHRZoKgkyEeBWQDm19H9DNDP2L4Y=,tag:er36wES3Qg3WILqXOCBWfg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:vLW0FVMnHJArjav5/fIPzE1U2fk=,iv:5nFCt7oWXvNgikxF/RnRQabzw7Y8cvgcVFkRElszuDI=,tag:bV4vAavVGUx3zb4gZ8cF7A==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:Myc5HlHY2ZwU1Fgpu0XWotDfgPMeWPo=,iv:mrR2NrpHkxfaFIcTRZo9YjCqY3TIZEInLfSS29TN+2k=,tag:JrW3wY64GwolYqY2PWaLpg==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cVNSbDRwVjBhbVROZ2Vi
            Z2t2ZW5Jcis2UXJtU2s0TnJ3ZlVGdmtHcVZzCkZ3VTFmM0JZTG0vNjZzQzQ1THZK
            N29xMHdDY2ZBUXFSeGFjZk9raDJteHcKLS0tIFpJSjBid3hUajNzU3psRTloRy9I
            NGxzVzVFMkNJUnZwZHRISzVrWWUwaXcKzvOlSL+7QtjaYhnl9sc5pdfYn3CwNQ/d
            IkiVEsJk4s877UnUL22W3euLi/Sc3NLjjfp68HzDvpgpqJ6BqujJQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T19:24:45Z"
    mac: ENC[AES256_GCM,data:n3GdvrMttJvVml/5+NU3Uw9L1toJR/qzUg190DoZE/bTkTqvJFVHMo3+7IvvJLmxdxJ7by/mnucBXCTk0RlJwFsueQuaGKKxCfr16U+gRneaJy4YKTzE82IJam7TpH4R75niv/m9H9PXy2yZajCIRszTZZI/LePhd8iRNg7EHQI=,iv:fD7rRnMFIfEUFJT1FqQAd/wDWfzT7m1xPE3TWgIxbs4=,tag:/ZG/kPmZYKZmNqbxCc2JgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
