apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerly
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ledgerly
  template:
    metadata:
      labels:
        app: ledgerly
    spec:
      securityContext:
        fsGroup: 101
        runAsUser: 101
        runAsGroup: 101

      imagePullSecrets:
        - name: docker-registry-auth
      containers:
        - name: ledgerly
          image: forgejo.colddev.net/coldb/ledgerly:pr-1@sha256:09dbb6f6e6078e4053a2826b6858eb06784f972829d2061caf622a735bb3d87b

          securityContext:
            allowPrivilegeEscalation: false

          imagePullPolicy: Always

          envFrom:
            - secretRef:
                name: ledgerly-secret

          ports:
            - containerPort: 8080
