apiVersion: v1
data:
    client-info.yml: ENC[AES256_GCM,data:j7YIpo1ULjb/ZdMIxWir7i3Boz5U1QZLDeMGN5p76a1SJ3zPyxeB4L7NRASfJrTZ1zWq9jRoTorWWLTCaotj1Rcj/bX3S6Zi/q4VMicXidRYrp4ASZHXMkLkK5VuPNIJBsJRiK+L0c73GRSJNoP35Wtw86M3wR64+btSEtoYnDj5wLSgLXAtgEtH+xmIwW6V4k3yhsZ56JvIUv1DbDOWe/LsZCT6zHKE4joHpn+g4Y8=,iv:bXjE1qw79263eHmwZSzeRr+oGvBGeKb/MsTfvMgv3DM=,tag:IH7QEIHZEVIjoibzqetZAw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: client-info-secret
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOU80RExBb1BXUnpGamww
            djA2REFSenRjeGR3UDVpbG1IWUh4MEVBalg4CmJGWkp3Mkx3amxkdUIyb2Vod3Ni
            d1VmT2hUOC8zU3dVQzR1YUp5U05BUW8KLS0tIE5kQ2lORXZNcks0ekFpU0FUSG1D
            Yko0MkVXcmJnRnBlOGVrNFVjeWdwQmMK3kWZxCnphRtVSElwmfraMsnehde8vJk5
            8QoZoSRFQqGcXJK8gFxnLwVYhbUFYCA2Sh99mVAsn6bUe4RAopl2Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-10T20:52:00Z"
    mac: ENC[AES256_GCM,data:vfcWpVYzjaO+Mxen7nU9psBspF42GB9EKiiYkuJDYe4/5oBAASY73rIMcjH5ZpjwaeQtQggHwFwDZzEx/WDsPoPlFkP2WZ6SGKILNYKz4nMWodY7PQgFPkyrKN10qLyrgUhHRGKoyuJzxjtZh61ZJyEVhyQamx8poUiku33CYLg=,iv:WOHCM1p1CdeaXvvVyYsTOxN7LKdQCBzKhtMVY3J4Sr8=,tag:VhYOdVoc25CGqNj4mgMKdg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
