apiVersion: v1
data:
    client-info.yml: ENC[AES256_GCM,data:ZcmAt6SZr8Ad8Ue/O8Rq9HGO5I6ODGo62w5O665HbEMKzhPiEuzCRQMXHGYTVckPZF4sMacC+XzD1v5MK5fr2m6Z216BOC9Oa75mu1XOqon3XHrXA1CUTD3NcNCfoEgGgBiiKKMyl/KDsxGH7RKsDgLdjO5GzC6JNyDAfSgkR/6FA/pXCkpt2D+M9JlNigMb7OOZ8llQyyDQQf7tmCFTrJqhZb2ntMijcn74ccgQebo=,iv:4lP+LS3xVIvdjHXVhtEJsiSyI9ODI1Ro9L7VDM06qM8=,tag:ea09CY+eAWO/rbJtkX6UIA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: client-info-secret
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcVpjOEhjWWp4RXZOV2Zo
            enZORWphZkxLUVRXMHpQdXA5Z2NZSnNteEhNCldSeXlFQjBNdzM0NEhUTTg0V1Iv
            cDdHZVV4eHNacU5ueGtna0hNdy9zSXcKLS0tIFpBSHFmR3hMd2ZDOXFreHRScTU1
            UVpUOWF1Y2ZEVUNzN1Y3aWZCaTQyL1EK+90V44TH02ImMoT5yQxFyTrWYyuk83S1
            bZKQU+GwJB/gtK4ybP4Qo9+Cv6pcCaOYSWVU/AXClqbqhuBN0CfY+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-10T19:54:03Z"
    mac: ENC[AES256_GCM,data:eUyMQe5WOsJ2oE6r0ElnR1T6azs73ekyINdwKq8j7v+Fb0b3KyB+Rk46gpbayyWehv6qjhdPXlgypUcEvj9GeeMb3ihJgaKJYCMAQpefRxiPkeNli9lgDcqp2ee1fHK3whUpIHxYkRSluqOuRGLGSqEKhB5l6uWEq9K0huOvB98=,iv:MSKwpHwV4i0Jrls7PtO/PPYg/odAEhHqJcIjKP+F+lQ=,tag:wQkTu//Frwb6sD6ebRyJDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
