{
 "title": "Cloudflare Tunnels (cloudflared)",
 "description": "Display Statistics for your Cloudflare Tunnels (cloudflared)",
 "tags": [
  "cloudflared",
  "Cloudflare Tunnels"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({__name__=~\"cloudflared_.*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cloudflare Edge Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_ha_connections{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Concurrent Requests",
   "type": "timeseries",
   "description": "Concurrent requests proxied through each tunnel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_concurrent_requests_per_tunnel{namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response By Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by(status_code) (increase(cloudflared_tunnel_response_by_code{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(cloudflared_tunnel_total_requests{namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Config Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(cloudflared_orchestration_config_version{namespace=~\"$namespace\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "increase(cloudflared_tunnel_request_errors{namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}