{
 "title": "Rocket.Chat Metrics",
 "description": "A comprehensive dashboard showing the behavior and performance of your Rocket.Chat application alongside current overall usage statistics. This dashboard provides a holistic view of your Rocket.Chat deployment, helping administrators monitor system health and user activity.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(rocketchat_info,cluster)"
    }
   },
   {
    "name": "Job",
    "query": {
     "query": "label_values(rocketchat_info,job)"
    }
   },
   {
    "name": "Namespace",
    "label": "Workspace",
    "query": {
     "query": "label_values(rocketchat_info{tenant_id=\"$Cluster\", job=\"$Job\"},namespace)"
    }
   },
   {
    "name": "Domain",
    "label": "Domain",
    "query": {
     "query": "label_values(rocketchat_info{tenant_id=\"$Cluster\"},site_url)"
    }
   },
   { "name": "baseline", "label": "baseline", "query": "1d,2d,1w,2w,4w,8w\n" }
  ]
 },
 "panels": [
  {
   "title": "Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users Online",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(rocketchat_users_online)" }
     ]
    },
    {
     "title": "Users Away",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_users_away{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})"
      }
     ]
    },
    {
     "title": "DDP Users",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rocketchat_ddp_connected_users{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})"
      }
     ]
    },
    {
     "title": "Users",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_users_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})"
      }
     ]
    },
    {
     "title": "Rooms",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_rooms_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_messages_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})"
      }
     ]
    },
    {
     "title": "Users Diff",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_users_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})"
      }
     ]
    },
    {
     "title": "Rooms  Diff",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_rooms_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})"
      }
     ]
    },
    {
     "title": "Messages  Diff",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "max(rocketchat_messages_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(rocketchat_metrics_requests{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Metrics Size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rocketchat_metrics_size{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NodeJS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Handles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_active_handles_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_active_requests_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Event loop lag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_size_used_bytes{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Per pod heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "nodejs_heap_size_used_bytes{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
       "legendFormat": "{{instance}} [{{space}}]"
      }
     ]
    },
    {
     "title": "GC - Seconds Running",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(nodejs_gc_pause_seconds_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (gctype)",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "GC - Bytes Freed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(increase(nodejs_gc_reclaimed_bytes_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DDP Rate Limiter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Limit by type",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{tenant_id=\"$Cluster\", namespace=\"$Namespace\", user_id!=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{tenant_id=\"$Cluster\", namespace=\"$Namespace\", user_id=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by method",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{tenant_id=\"$Cluster\", namespace=\"$Namespace\", user_id!=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{tenant_id=\"$Cluster\", namespace=\"$Namespace\", user_id=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by userId",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (user_id)",
       "legendFormat": "{{user_id}}"
      }
     ]
    },
    {
     "title": "Limit by connectionId",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{tenant_id=\"$Cluster\", namespace=\"$Namespace\", user_id!=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{tenant_id=\"$Cluster\", namespace=\"$Namespace\", user_id=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (null)"
      }
     ]
    }
   ]
  },
  { "title": "RocketChat Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Messages Sent (30m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(rocketchat_message_sent{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[30m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages Sent Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rocketchat_messages_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages Round Trip",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(increase(rocketchat_message_sent{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m]))",
     "legendFormat": "Messages"
    },
    {
     "expr": "avg(rocketchat_messages_roundtrip_time_summary{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}) by (quantile)",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "avg(rocketchat_messages_roundtrip_time_summary_sum{tenant_id=\"$Cluster\", namespace=\"$Namespace\"} / rocketchat_messages_roundtrip_time_summary_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "avg(rate(rocketchat_messages_roundtrip_time_summary_sum{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m]) / rate(rocketchat_messages_roundtrip_time_summary_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m]))",
     "legendFormat": "Rate"
    },
    {
     "expr": "rate(rocketchat_messages_roundtrip_time{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Presence",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rocketchat_users_online{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "Online"
    },
    {
     "expr": "avg(rocketchat_users_away{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "Away"
    }
   ]
  },
  {
   "title": "Users & Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketchat_ddp_connected_users{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "Connected Users"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "All Sessions"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_auth{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "Authenticated Sessions "
    }
   ]
  },
  {
   "title": "Web Socket Connections per pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rocketchat_ddp_connected_users{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "users_connected{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Apps Installed / Disabled / Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rocketchat_apps_installed{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
     "legendFormat": "{{instance}} - installed"
    },
    {
     "expr": "rocketchat_apps_enabled{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
     "legendFormat": "{{instance}} - enabled"
    },
    {
     "expr": "rocketchat_apps_failed{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
     "legendFormat": "{{instance}} - failed"
    }
   ]
  },
  {
   "title": "Oplog",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(increase(rocketchat_oplog{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (collection,op)",
     "legendFormat": "{{collection}}/{{op}}"
    }
   ]
  },
  {
   "title": "Oplog By instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(increase(rocketchat_oplog{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rocketchat_oplog_queue{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Push Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rocketchat_push_queue{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Meteor Facts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_facts{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}) by (pkg, fact)",
     "legendFormat": "{{pkg}} {{fact}}"
    }
   ]
  },
  {
   "title": "Total of Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(rocketchat_users_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Total of Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(rocketchat_rooms_total{tenant_id=\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "Rooms"
    }
   ]
  },
  {
   "title": "Notifications / Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(rocketchat_notification_sent{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (notification_type)",
     "legendFormat": "{{notification_type}}"
    }
   ]
  },
  { "title": "Methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Meteor Methods Total Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_methods{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}) by (method) * sum(increase(rocketchat_meteor_methods_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Meteor Methods Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_methods{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Meteor Methods Calls / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rocketchat_meteor_methods_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Meteor Subscription Total Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_subscriptions{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}) by (subscription) * sum(increase(rocketchat_meteor_subscriptions_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (subscription)",
     "legendFormat": "{{subscription}}"
    }
   ]
  },
  {
   "title": "Meteor Subscription Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_subscriptions{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}) by (subscription)",
     "legendFormat": "{{subscription}}"
    }
   ]
  },
  {
   "title": "Meteor Subscription Calls / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rocketchat_meteor_subscriptions_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (subscription)",
     "legendFormat": "{{subscription}}"
    }
   ]
  },
  { "title": "Callbacks & Hooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } },
  {
   "title": "Callbacks Total Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rocketchat_callbacks{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}) by (callback) * sum(increase(rocketchat_callbacks_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (callback)",
     "legendFormat": "{{callback}}"
    }
   ]
  },
  {
   "title": "Callbacks Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(rocketchat_callbacks{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (callback)",
     "legendFormat": "{{callback}}"
    }
   ]
  },
  {
   "title": "Callbacks Calls / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(rocketchat_callbacks_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (callback)",
     "legendFormat": "{{callback}}"
    }
   ]
  },
  {
   "title": "Hooks Total Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rocketchat_hooks{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}) by (hook) * sum(increase(rocketchat_hooks_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (hook)",
     "legendFormat": "{{hook}}"
    }
   ]
  },
  {
   "title": "Hooks Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(rocketchat_hooks{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (hook)",
     "legendFormat": "{{hook}}"
    }
   ]
  },
  {
   "title": "Hooks Calls / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(rocketchat_hooks_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (hook)",
     "legendFormat": "{{hook}}"
    }
   ]
  },
  { "title": "REST API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 } },
  {
   "title": "REST API Total Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rocketchat_rest_api{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}) by (entrypoint) * sum(increase(rocketchat_rest_api_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "REST API Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(rocketchat_rest_api{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "REST API Calls / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rocketchat_rest_api_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "REST API Calls / Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(rocketchat_rest_api_count{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[5m])) / (sum(users_connected{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}) + sum(rocketchat_ddp_connected_users{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}))",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  { "title": "Baseline comparisons", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 208 } },
  {
   "title": "Messages Sent compared to $baseline ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(increase(rocketchat_message_sent{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[30m])) - \n  sum(increase(rocketchat_message_sent{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[30m] offset $baseline))\n) \n/\nsum(increase(rocketchat_message_sent{tenant_id=\"$Cluster\", namespace=\"$Namespace\"}[30m] offset $baseline))\n",
     "legendFormat": "Delta compared with $baseline"
    }
   ]
  }
 ]
}