apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
  - target:
      group: storage.k8s.io
      version: v1
      kind: StorageClass
      name: local-path
    patch: |-
      - op: remove
        path: /metadata/annotations/storageclass.kubernetes.io~1is-default-class
