apiVersion: v1
stringData:
    token: ENC[AES256_GCM,data:B71LM7VeGPkZYNn9pqB3AL0hTYf7fO4gajfuC/xxWHqRiWkIzh6FfHshG68xqlWo1U1coRAuTn8+k+xMeq1C3JrATsyNk3ZKxtMkBCaaTQLeS2EKSwYeEbEUx65mcAGqmEBqsaxq9Nqd68LtiJx4gajNOHLnBV5w0UqwoBGl/xrTKZAwgKCKDfItX0iNajAMr+GqdGVylPEr3UGGPEqVjHdGefNyFaTQdhf6Ok0g/9dOulNS28EO6A==,iv:E955+T2LG/q9wImOPttoV2wvMlq+v5n4guWiIHpwWQo=,tag:oGs6x7zxn/yIP9J2jqTClg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUkJtSkY0bU5pOUhrU0ZP
            VnlrU0dyQWVLZHJDWDlUTEJMZHBiczhseWdNCnBXRDV1K2VJeW1QSy8yTGtycWV0
            VlgrSXZjaVRFaXNFN25CbjdPdm5EOVkKLS0tIGt0MTduc3BBcHp2QzZ2ZUVpcFZY
            TWhHZXhJdVVvNlhYSXgxbXRLTHpDWEUKCE7B354Fbhs0pCH/htqlYQDwEHtsEXa3
            cBNU4UdUCHphIWRNGtZgkFgXjeShZYTCVP9HR7EE2xjiUWjyyK5kww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T11:28:14Z"
    mac: ENC[AES256_GCM,data:jFjr1BiBsnnDRDTk+dn4p7Sg0dqyuARoariULjGau+4G3OQxXA8sa8CiQl5rjRUJrS4vLn/awXXbOJHH9XqWAqjcKnVqo7bHewiDqrskO2BVlniP3bwvynJJacXPEesp1UqF3Qi/MZ5B3UP3NC8wcHMfz/KhzKaaAavo8pyaPfs=,iv:VzJF2HaUTl8+5G7HWSBi7rvshaxCuYh05RW3TL+6ksU=,tag:EeqGV3gg7Bgy7MstGnhQpA==,type:str]
    version: 3.13.0
