apiVersion: v1
data:
    token: ENC[AES256_GCM,data:S3tIS2VvFIPuEL5d/q83pK6wQlzNJv3sWUKPygl0568ZzBhcV/jcNHOe/zMs7Hda6Sms/K/ySm0kNMcWAYK4mh3xJ85VnoW4ZWJUlfJRfhORTFjsUeKrd72aHVMJBATVuKcbhQLdplFtCsSQrHJ4HFgOJTb96pLlz+9NMWyvY73aAYxvDjGyWlr7O5s1asOL7pqTA7i9z3eE7JGY++PgOpBkLei37HysAT2bmCrJ0F1RQe2+EiEipg==,iv:PZIu9QIwccYOpX1uQXwSYb97F6hdwIT73XOfyRN4aFE=,tag:CJkaeziaX8/UuRqgFc1Pjg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUkJtSkY0bU5pOUhrU0ZP
            VnlrU0dyQWVLZHJDWDlUTEJMZHBiczhseWdNCnBXRDV1K2VJeW1QSy8yTGtycWV0
            VlgrSXZjaVRFaXNFN25CbjdPdm5EOVkKLS0tIGt0MTduc3BBcHp2QzZ2ZUVpcFZY
            TWhHZXhJdVVvNlhYSXgxbXRLTHpDWEUKCE7B354Fbhs0pCH/htqlYQDwEHtsEXa3
            cBNU4UdUCHphIWRNGtZgkFgXjeShZYTCVP9HR7EE2xjiUWjyyK5kww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lu89hj3qppwuccx8nn5qq2dkny3kucgud7d4mallc7kw54a6xs7qwwfuez
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T11:15:31Z"
    mac: ENC[AES256_GCM,data:uMnt8yJIX4d3bSGxAU8UQJ+iGKDOvd+uuZ0LwBoO48xu21uKHPMuf+wgpYR3mEwbalK4UCS8yyqoA0PYS80injzNeF3wiHMJAtrp9p8zuA5+ztViiO2rWqby45HA6PgidE9kFTY0UioWABNIohGY/2p9Pl3O0o486NcnKYWhcEE=,iv:yt89TQDdRSuwCLrvS3RZwGG7S+idSzhA+1mpuUnoukk=,tag:rFt6o1PXj0ywaU8hHllVqA==,type:str]
    version: 3.13.0
