apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ledgerly
resources:
  - configmap.enc.yaml
  - ../../base/ledgerly/
  - cloudflared.enc.yaml
  - ../../../shared/cloudflared/
