apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      pod: cloudflared
  namespaceSelector:
    matchNames:
      - linkding
      - rocketchat
      - audiobookself
  endpoints:
    - port: 2000
      path: /metrics
      interval: 30s
      honorLabels: true
