apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cloudflared-metrics
  namespaceSelector:
    matchNames:
      - linkding
      - rocketchat
      - audiobookshelf
  endpoints:
    - port: "metrics"
      path: /metrics
      interval: 30s
      honorLabels: true
