apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "75.8.*"
      # version: "66.2.2"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: siim
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana-staging.colddev.net
        tls:
          - secretName: grafana-tls-secret
            hosts:
              - grafana-staging.colddev.net

      sidecar:
        datasources:
          enabled: true
          label: grafana_datasource
          labelValue: "1"
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          # Allow discovery in all namespaces for dashboards
          searchNamespace: ALL
          provider:
            allowUiUpdates: true

      persistence:
        enabled: true
        storageClassName: "synology-iscsi"
        type: pvc
        accessModes:
          - ReadWriteOnce
        size: 4Gi
