apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db-cluster-v1
spec:
  instances: 3

  monitoring:
    enablePodMonitor: true

  storage:
    size: 5Gi
    storageClassName: "synology-iscsi"
