apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db-production-cluster-v1
spec:
  instances: 3

  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-db-app-user-secret

  monitoring:
    enablePodMonitor: true

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: "synology-iscsi-retain"
