apiVersion: v1
data:
    password: ENC[AES256_GCM,data:qJh+bQ==,iv:xqJqwa7HQh9lKlijoeQ6W10GLXPKPOiNvZcXepn8Lys=,tag:oCDeq83P4bFFF7en16AOJw==,type:str]
    user: ENC[AES256_GCM,data:6jN0OjcVgwohC6hlvcRr32udRrirms/paPEREQ==,iv:i10rjQnKdgDY4GNnLFHpvrEYBASh0A751ZCQtGupaiI=,tag:Lvya5M8hRpam/qPUfVpkdg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-secret
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMTR1RDY0dUxJRVBzN0c1
            cW9sRkJTTmEzU2ZWMWNOK3hLQXZEQUk4TlZjCitRaE9ZNjNvZGt6bWVHNkxGNkpv
            eDFNRTBiR0dBYkdRVVV0MC94MlFiVFEKLS0tIHVRN0dndjhMdm4zSTIvb29leGxS
            UnpIb3V2RVUwRFNkR0QxMEhQZEQ3RFUKLrwlS/QMNfbuaMPiWeYyjmI1wUPl20X4
            decmGDU9vIDaqosIvGaytW971GJM2djtvgOUY4dypxgpUYnYA8mYOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-04T16:06:23Z"
    mac: ENC[AES256_GCM,data:TmMq79tPXcysaGQHJrktxYKXUO41QetTr5yoN65TYAOxjUbhTnmteXzIYsEEhrBHRIXPwdHX31c1qKZA724Xkb0HqNNMehGvX8nMjhPrWmCVbz1Gt89JcPEIwsxSx/XsRyo+mg84OEUhus69xgoAsW8f5+LQootNifs1yX4UOZ4=,iv:EgL4zuYbuZ/NynXefV4pps9sjvI3XEgtT/BS9xxP5xM=,tag:ihhn9vvimrIFrjLVJsDS8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
