apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-longhorn-backup-pvc
spec:
  storageClassName: "longhorn-retain-backup"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
