apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  storageClassName: "synology-iscsi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
