apiVersion: v1
kind: Secret
metadata:
    name: aws-backup-credentials
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:99brYxSUQDWfBGciW2bDWHdWhco=,iv:73U88zNgOM3qBevY3STd+5HyE3mGkPGXcyqCSzIWiJs=,tag:60dscQrexkNihoHoYs62sw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aUxtwil3V3oD3OnIMo2f6ExErihyidDoPcir6pnBhDWFSIgAn6fkEQ==,iv:5L1CfjcerHBH/DjlRSi9KFBO8b2kyOHFt/ynG1pJ+ag=,tag:jwD6zFgaggVHMswlUCF6EA==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQVRMUWlVZG1qbFhMa3V3
            MHlDTDA1RHdNUnFGNG9QT0RHdGs2T2EySGlVCitxTVYxNjZDeHNJaXBjK2pab0RB
            TUVBM2M1bFE2Ymx6SlNzZlZBNTVxOE0KLS0tIE5JOS9jZnAvdXZ6RzNVYS8wWUdI
            UWNWZjFVQ3NHWG9zaFlqU1N5ZDlYc3MKftvYWF2EWZALrMSpti7DLsgUSq4IwNcV
            8qLD7sH3Oo9s3bPXBzt4i7JI/n66roaQHJI9NTMTBaRojhizj8gbEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T16:37:59Z"
    mac: ENC[AES256_GCM,data:ybRJEepI/amSp0dkJpdc5a4efpS8B0tcnLyeBtitsvfS5rmkpMeynR6QxrYknoRJa3ohl9zSpdXaz1E6Zq6WBfy2CDrqKCv+XAuS3JRaT0Rr2I6Q+S96rwQlxv+EZBFYp7dpxXFnv29QLAQSc7vFdu78Fl3OYmVtm7wVbhZa4aE=,iv:u870v+ekNxNdz2SciJLA0lfzh/dY0dYRFDu04pjy9k0=,tag:/Uc1DKRok1NeI/lJGQfvww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
