apiVersion: v1
kind: Secret
metadata:
    name: docker-registry-auth
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: testing-public
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: testing-public
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:DT4LzhbaK4lSg1WQQ0PzwsS428DGf11Le6hUqKmQlcWlMnUjHu6SykOU2nSSE4uNxMtLDhy+XmaduI+e4o7YWU/k5Na2JvG1roAIZu4HsJk+UFBl6PVcERgw/JKCfCiv6vo8b92I7r7mNOOz2XaI1OFuSNKRfVxb4CCxK9ugEOv7EHqbN2WA3nQ0Um2uuN+1LRmb8y03edb/jjNXV8mnePn1mZmeNTqp,iv:OpxpmXLS0WYr1t3lzbZ2AhHyL5uF/vid4QxKixmtXFM=,tag:rp/T1tOwXycJLAy8ivBebg==,type:str]
sops:
    age:
        - recipient: age1dsevcxza33vhmq3hn7693jcla2l2peur7shm40pk2dsfuvh2cvus3ut5k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTy9zZW1EWk85ZkNrRXR0
            UWVIbklqVlc5b0ZZczBDN2RKYis4QS9CNkUwCnlyT2xMT09GdXRrYWJJaDVKSFlQ
            Y29sVGMybVJrVzNGOFdhU2xoL0NGTXMKLS0tIFdDejJGc1lBV3BiMm41OTBENlpY
            ZVdHeWx2T2xKK0liR09yN2k2elVPMFEKHDnzGlnL7+EWBs5Twpd7L6UftCKqG/iM
            naOQHKhgAqzwIoK3GX+FAvihIX/OdHy+0tCUELNsWHcINiZNYRJf5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T17:28:08Z"
    mac: ENC[AES256_GCM,data:RfzAW9dvh28vmfe0VPTvYHosiUuMX5aY2lZYIEM3+6+VQ+rRm2dfiR/lehdiJzfSJqKVns0V203u5W8kK0EeA6MsWJCHVz9zKiErxFewFGMn3XeB7Og5K5ENrFcmssxJfsdTogDR//icKWMVHg8XG+Is9sAxQiX8sOFT7h74bW0=,iv:gc/j6oiASHaXNLWHBy1UkDqa1j/YpiWVf6A8qnyTn+c=,tag:u+12I2Lh+TcqkuO57Gyaew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
